other/trunk/rails_app/home_io/config/routes.rb
HomeIo::Application.routes.draw do

  devise_for :users

  resources :meas_type_groups do
    resource :meas_type_group_graph, :only => [:show]
    member do
      get :latest
    end
  end

  resources :day_statistics, :only => [:index, :show]

  resource :dashboard, :only => [:index, :show]

  resources :home_archives

  resources :comments do
    resources :comments
  end

  resources :action_events do
    resources :comments
  end

  resources :overseers do

    get :status, :on => :collection
    member do
      put :enable, :action => :enable
      put :disable, :action => :disable
    end
  end

  resources :action_types, :except => [:new, :create, :edit, :update, :delete] do
    resources :action_events
    get :execute, :on => :member
  end

  resources :memos

  resources :meas_types, :only => [:show, :edit, :index, :update] do
    resources :meas_archives do
      get :chart, :on => :collection
      resources :comments
    end

    resource :meas_cache
  end

  resources :meas_caches, :only => [:index] do
  end

  resources :cities do
    resources :weather_metar_archives, :only => [:index, :show]
    resources :weather_archives, :only => [:index, :show]
  end

  resource :user_session do
    get :logout
  end

  resource :account, :controller => "users"
  resources :users

  match 'mobile', :controller => "welcome", :action => "index", :mobile_device => 't'
  match 'desktop', :controller => "welcome", :action => "index", :mobile_device => 'f'

  root :to => "welcome#index"

end

other/trunk/rails_app/home_io/app/controllers/memos_controller.rb
class MemosController < ApplicationController
  #load_and_authorize_resource
  
  # GET /memos
  # GET /memos.xml
  def index
    authorize! :read, Memo
    @memos = Memo.paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @memos }
    end
  end

  # GET /memos/1
  # GET /memos/1.xml
  def show
    authorize! :read, Memo
    @memo = Memo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @memo }
    end
  end

  # GET /memos/new
  # GET /memos/new.xml
  def new
    authorize! :create, Memo
    @memo = Memo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @memo }
    end
  end

  # GET /memos/1/edit
  def edit
    @memo = Memo.find(params[:id])
    authorize! :manage, @memo
  end

  # POST /memos
  # POST /memos.xml
  def create
    authorize! :create, Memo
    @memo = Memo.new(params[:memo])
    @memo.user_id = current_user.id

    respond_to do |format|
      if @memo.save
        format.html { redirect_to(@memo, :notice => 'Memo was successfully created.') }
        format.xml  { render :xml => @memo, :status => :created, :location => @memo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @memo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /memos/1
  # PUT /memos/1.xml
  def update
    @memo = Memo.find(params[:id])
    authorize! :manage, @memo
    @memo.user_id = current_user.id

    respond_to do |format|
      if @memo.update_attributes(params[:memo])
        format.html { redirect_to(@memo, :notice => 'Memo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @memo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /memos/1
  # DELETE /memos/1.xml
  def destroy
    @memo = Memo.find(params[:id])
    authorize! :manage, @memo
    @memo.destroy

    respond_to do |format|
      format.html { redirect_to(memos_url) }
      format.xml  { head :ok }
    end
  end
end

other/trunk/rails_app/home_io/app/helpers/memos_helper.rb
module MemosHelper
end

other/trunk/rails_app/home_io/app/views/memos/_form.html.erb
<%= form_for(@memo) do |f| %>
  <% if @memo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@memo.errors.count, "error") %> prohibited this memo from being saved:</h2>

      <ul>
      <% @memo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

other/trunk/rails_app/home_io/app/views/memos/edit.html.erb
<h1>Editing memo</h1>

<%= render 'form' %>

<%= link_to 'Show', @memo %> |
<%= link_to 'Back', memos_path %>

other/trunk/rails_app/home_io/app/views/memos/index.html.haml
%h2= "Memos"

%table.data_table
  %thead
    %tr
      %th= "Title"
      %th= "User"
      %th= "Created"
      %th= "Updated"
      %th{:colspan => 3}= "Actions"

  - @memos.each do |memo|
    %tr{:class => cycle("even", "odd")}
      %td= memo.title

      - unless memo.user.nil?
        %td= memo.user.login
      -else
        %td

      %td= memo.created_at
      %td= memo.updated_at

      %td= link_to 'Show', memo

      - if can?(:manage, memo)
        %td= link_to 'Edit', edit_memo_path(memo)
      - else
        %td

      - if can?(:manage, memo)
        %td= link_to 'Destroy', memo, :confirm => 'Are you sure?', :method => :delete
      - else
        %td

= link_to "New memo", new_memo_path

%hr
%p= will_paginate @memos
%p= page_entries_info @memos

other/trunk/rails_app/home_io/app/views/memos/new.html.erb
<h1>New memo</h1>

<%= render 'form' %>

<%= link_to 'Back', memos_path %>

other/trunk/rails_app/home_io/app/views/memos/show.html.haml
%h2
  = "Memo: "
  = @memo.title

%p
  %b= "Content"
  = @memo.text


%hr

%p
  = "Content"
  = @memo.text

%p
  = "Created at "
  = @memo.created_at

%p
  = "Updated at "
  = @memo.updated_at

%hr

= link_to 'Edit', edit_memo_path(@memo)
= link_to 'Back', memos_path