other/trunk/rails_app/home_io/config/routes.rb
HomeIo::Application.routes.draw do

  devise_for :users

  resources :meas_type_groups do
    resource :meas_type_group_graph, :only => [:show]
    member do
      get :latest
    end
  end

  resources :day_statistics, :only => [:index, :show]

  resource :dashboard, :only => [:index, :show]

  resources :home_archives

  resources :comments do
    resources :comments
  end

  resources :action_events do
    resources :comments
  end

  resources :overseers do

    get :status, :on => :collection
    member do
      put :enable, :action => :enable
      put :disable, :action => :disable
    end
  end

  resources :action_types, :except => [:new, :create, :edit, :update, :delete] do
    resources :action_events
    get :execute, :on => :member
  end

  resources :memos

  resources :meas_types, :only => [:show, :edit, :index, :update] do
    resources :meas_archives do
      get :chart, :on => :collection
      resources :comments
    end

    resource :meas_cache
  end

  resources :meas_caches, :only => [:index] do
  end

  resources :cities do
    resources :weather_metar_archives, :only => [:index, :show]
    resources :weather_archives, :only => [:index, :show]
  end

  resource :user_session do
    get :logout
  end

  resource :account, :controller => "users"
  resources :users

  match 'mobile', :controller => "welcome", :action => "index", :mobile_device => 't'
  match 'desktop', :controller => "welcome", :action => "index", :mobile_device => 'f'

  root :to => "welcome#index"

end

other/trunk/rails_app/home_io/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
  
end

other/trunk/rails_app/home_io/app/helpers/welcome_helper.rb
module WelcomeHelper
end

other/trunk/rails_app/home_io/app/views/welcome/index.haml
%h2= "Welcome"

- if current_user

  %div{:style => 'height: 200px; width: 100%; align: center;', :align => 'center'}
    %div.rounded_box
      = link_to "Current measurements", meas_caches_path
    %div.rounded_box
      = link_to "Actions", action_types_path
    %div.rounded_box
      = link_to "Last executed actions", action_type_action_events_path('all')
    %div.rounded_box
      = link_to "Overseers status", status_overseers_path

    %br

- else
  = "Please login"