other/trunk/rails_app/home_io/config/routes.rb
HomeIo::Application.routes.draw do

  devise_for :users

  resources :meas_type_groups do
    resource :meas_type_group_graph, :only => [:show]
    member do
      get :latest
    end
  end

  resources :day_statistics, :only => [:index, :show]

  resource :dashboard, :only => [:index, :show]

  resources :home_archives

  resources :comments do
    resources :comments
  end

  resources :action_events do
    resources :comments
  end

  resources :overseers do

    get :status, :on => :collection
    member do
      put :enable, :action => :enable
      put :disable, :action => :disable
    end
  end

  resources :action_types, :except => [:new, :create, :edit, :update, :delete] do
    resources :action_events
    get :execute, :on => :member
  end

  resources :memos

  resources :meas_types, :only => [:show, :edit, :index, :update] do
    resources :meas_archives do
      get :chart, :on => :collection
      resources :comments
    end

    resource :meas_cache
  end

  resources :meas_caches, :only => [:index] do
  end

  resources :cities do
    resources :weather_metar_archives, :only => [:index, :show]
    resources :weather_archives, :only => [:index, :show]
  end

  resource :user_session do
    get :logout
  end

  resource :account, :controller => "users"
  resources :users

  match 'mobile', :controller => "welcome", :action => "index", :mobile_device => 't'
  match 'desktop', :controller => "welcome", :action => "index", :mobile_device => 'f'

  root :to => "welcome#index"

end

other/trunk/rails_app/home_io/app/helpers/weathers_helper.rb
module WeathersHelper
end

other/trunk/rails_app/home_io/app/views/weather/_weather.html.haml
%h2= "Weather detail"

%ul.details
  %li
    = "City"
    = " - "
    %span.parameter= link_to weather.city.name, city_path(weather.city)
  - if weather.kind_of? WeatherMetarArchive
    %li
      = "Raw"
      = " - "
      %span.parameter= weather.raw
  - if weather.kind_of? WeatherArchive
    %li
      = "Provider"
      = " - "
      %span.parameter= weather.weather_provider.name

  - date_from = l weather.time_from, :format => :date
  - date_to = l weather.time_to, :format => :date
  %li
    -# if dates are equal show only 'date'
    - if not date_from == date_to
      = "Date from"
    - else
      = "Date"
    = " - "
    %span.parameter= date_from

  %li
    = "Time from"
    = " - "
    %span.parameter= l weather.time_from, :format => :pro_time

  -# show only when there is another day
  - if not date_from == date_to
    %li
      = "Date to"
      = " - "
      %span.parameter= l weather.time_to, :format => :date


  %li
    = "Time to"
    = " - "
    %span.parameter= l weather.time_to, :format => :pro_time


  %li
    = "Id"
    = " - "
    %span.parameter= weather.id

  - if not weather.temperature.nil?
    %li
      = "Temperature"
      = " - "
      %span.parameter= weather.temperature
      = " C"

  - if not weather.wind.nil?
    %li
      = "Wind"
      = " - "
      %span.parameter= "%.1f" % weather.wind
      = " m/s"

  - if not weather.pressure.nil?
    %li
      = "Pressure"
      = " - "
      %span.parameter= weather.pressure
      = " hPa"

  - if weather.kind_of? WeatherMetarArchive
    %li
      = "Rain (metar)"
      = " - "
      %span.parameter= weather.rain_metar
  - if weather.kind_of? WeatherArchive
    - if not weather.rain.nil?
      %li
        = "Rain [mm]"
        = " - "
        %span.parameter= "%.1f" % weather.rain
        = " mm"

  - if weather.kind_of? WeatherMetarArchive
    %li
      = "Snow (metar)"
      = " - "
      %span.parameter= weather.snow_metar
  - if weather.kind_of? WeatherArchive
    - if not weather.snow.nil?
      %li
        = "Snow"
        = " - "
        %span.parameter= "%.1f" % weather.snow
        = " mm"

other/trunk/rails_app/home_io/app/views/weather/_weather_row.html.haml
- if weather_row.kind_of? WeatherMetarArchive
  - title = "Metar code: #{weather_row.raw}"
- else
  - title = nil
%tr{:class => cycle("even", "odd"), :title => title}
  - if weather_row.kind_of? WeatherArchive
    %td= weather_row.weather_provider.name

  %td= l weather_row.time_from, :format => :date
  %td= l weather_row.time_from, :format => :pro_time
  %td= l weather_row.time_to, :format => :pro_time
  %td= weather_row.temperature
  %td= "%.1f" % weather_row.wind
  %td= weather_row.pressure
  %td
    - if weather_row.kind_of? WeatherMetarArchive
      = weather_row.rain_metar
    - if weather_row.kind_of? WeatherArchive
      - if not weather_row.rain.nil?
        = "%.1f" % weather_row.rain

  %td
    - if weather_row.kind_of? WeatherMetarArchive
      = weather_row.snow_metar
    - if weather_row.kind_of? WeatherArchive
      - if not weather_row.snow.nil?
        = "%.1f" % weather_row.snow
  %td
    - if weather_row.kind_of? WeatherMetarArchive
      = link_to "Detail", city_weather_metar_archive_path(params[:city_id], weather_row)
    - if weather_row.kind_of? WeatherArchive
      = link_to "Detail", city_weather_archive_path(params[:city_id], weather_row)