other/trunk/rails_app/home_io/config/routes.rb
HomeIo::Application.routes.draw do

  devise_for :users

  resources :meas_type_groups do
    resource :meas_type_group_graph, :only => [:show]
    member do
      get :latest
    end
  end

  resources :day_statistics, :only => [:index, :show]

  resource :dashboard, :only => [:index, :show]

  resources :home_archives

  resources :comments do
    resources :comments
  end

  resources :action_events do
    resources :comments
  end

  resources :overseers do

    get :status, :on => :collection
    member do
      put :enable, :action => :enable
      put :disable, :action => :disable
    end
  end

  resources :action_types, :except => [:new, :create, :edit, :update, :delete] do
    resources :action_events
    get :execute, :on => :member
  end

  resources :memos

  resources :meas_types, :only => [:show, :edit, :index, :update] do
    resources :meas_archives do
      get :chart, :on => :collection
      resources :comments
    end

    resource :meas_cache
  end

  resources :meas_caches, :only => [:index] do
  end

  resources :cities do
    resources :weather_metar_archives, :only => [:index, :show]
    resources :weather_archives, :only => [:index, :show]
  end

  resource :user_session do
    get :logout
  end

  resource :account, :controller => "users"
  resources :users

  match 'mobile', :controller => "welcome", :action => "index", :mobile_device => 't'
  match 'desktop', :controller => "welcome", :action => "index", :mobile_device => 'f'

  root :to => "welcome#index"

end

other/trunk/rails_app/home_io/app/controllers/day_statistics_controller.rb
class DayStatisticsController < ApplicationController
  # GET /day_statistics
  # GET /day_statistics.xml
  def index
    @day_statistics = DayStatistic.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @day_statistics }
    end
  end

  # GET /day_statistics/1
  # GET /day_statistics/1.xml
  def show
    @day_statistic = DayStatistic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @day_statistic }
    end
  end

end

other/trunk/rails_app/home_io/app/helpers/day_statistics_helper.rb
module DayStatisticsHelper
end

other/trunk/rails_app/home_io/app/views/day_statistics/_form.html.erb
<%= form_for(@day_statistic) do |f| %>
  <% if @day_statistic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@day_statistic.errors.count, "error") %> prohibited this day_statistic from being saved:</h2>

      <ul>
      <% @day_statistic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

other/trunk/rails_app/home_io/app/views/day_statistics/edit.html.erb
<h1>Editing day_statistic</h1>

<%= render 'form' %>

<%= link_to 'Show', @day_statistic %> |
<%= link_to 'Back', day_statistics_path %>

other/trunk/rails_app/home_io/app/views/day_statistics/index.html.erb
<h1>Listing day_statistics</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @day_statistics.each do |day_statistic| %>
  <tr>
    <td><%= link_to 'Show', day_statistic %></td>
    <td><%= link_to 'Edit', edit_day_statistic_path(day_statistic) %></td>
    <td><%= link_to 'Destroy', day_statistic, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Day statistic', new_day_statistic_path %>

other/trunk/rails_app/home_io/app/views/day_statistics/new.html.erb
<h1>New day_statistic</h1>

<%= render 'form' %>

<%= link_to 'Back', day_statistics_path %>

other/trunk/rails_app/home_io/app/views/day_statistics/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_day_statistic_path(@day_statistic) %> |
<%= link_to 'Back', day_statistics_path %>